### ISSUE TITLE
pytest execution breaks if wrong expect file provided. 

### ISSUE THREAD

**Issue by jayjoshi64** [gsnedders/pytest-expect#9]
By any chance if an existing file is provided which does not follow the standard of an expect file, the pytest execution breaks 
```
(mypython) C:\Jay\Contrubutions>python -m pytest test_expect -vv --xfail-file jay.txt
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\jay\contrubutions\mypython\lib\site-packages\pytest_expect\expect.py", line 50, in pytest_configure
INTERNALERROR>     exp.load_expectations()
INTERNALERROR>   File "c:\jay\contrubutions\mypython\lib\site-packages\pytest_expect\expect.py", line 77, in load_expectations
INTERNALERROR>     self.expect_xfail = self._parse_legacy_file(fp)
INTERNALERROR>   File "c:\jay\contrubutions\mypython\lib\site-packages\pytest_expect\expect.py", line 147, in _parse_legacy_file
INTERNALERROR>     if PY3 and b'py_version' in state:
INTERNALERROR> TypeError: argument of type 'int' is not iterable
INTERNALERROR>
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR>
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Jay\Contrubutions\mypython\lib\site-packages\_pytest\main.py", line 187, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "C:\Jay\Contrubutions\mypython\lib\site-packages\_pytest\config\__init__.py", line 820, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "C:\Jay\Contrubutions\mypython\lib\site-packages\pluggy\hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Jay\Contrubutions\mypython\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Jay\Contrubutions\mypython\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "C:\Jay\Contrubutions\mypython\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Jay\Contrubutions\mypython\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Jay\Contrubutions\mypython\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\jay\contrubutions\mypython\lib\site-packages\pytest_expect\expect.py", line 52, in pytest_configure
INTERNALERROR>     config.warn("W1", "failed to load expectation file")
INTERNALERROR> AttributeError: 'Config' object has no attribute 'warn'
```

The issue should be handled gracefully. The user should be notified that the file provided is not an expect file.

**Comment by jayjoshi-crest** [comment]
@gsnedders Can you please take a look at the PR: #12 ?

**Comment by jayjoshi-crest** [comment]
@gsnedders  I believe this is an important bug that should be fixed.  can you please look into this?
